version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - VITE_RUBY_HOST=0.0.0.0
    command: bin/server
    volumes:
      - .:/app/:cached
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules:cached
      - bundle:/bundle:cached
    ports:
      - 5000:5000
      - 3036:3036
    tty: true
    stdin_open: true
    links:
      - db
      # - redis
      # - mailcathcer

#  mailcatcher:
#    image: 'schickling/mailcatcher'
#    ports:
#      - "1025:1025"
#      - "1080:1080"
#  redis:
#    image: redis
#    ports:
#      - '6379:6379'
#
volumes:
  postgres_data:
  rails_cache:
  node_modules:
  bundle:

